---
- hosts: all
  pre_tasks:
    - debug: var=playbook_dir
  tasks:
    - name: test from outer playbook
      copy:
        src: "{{ test_src }}"
        dest: /tmp/some.file.outer

- import_playbook: playbooks/test_inner.yml
